#String format
table = int(input("Please enter number to print table"))
print(f"{table}*1 ={table}")
print(f"{table}*2={table}")
print(f"{table}*3={table}")
print(f"{table}*4={table}")
print(f"{table}*5={table}")
print(f"{table}*6={table}")
print(f"{table}*7={table}")
print(f"{table}*8={table}")
print(f"{table}*9={table}")
print(f"{table}*10={table}")
